/**
 * Scale names taken from the Ornament and Crime source code:
 * https://raw.githubusercontent.com/mxmxmx/O_C/659f97e09145c526c89839a30714782e99ab8fc7/software/o_c_REV/OC_scales.cpp
 *
 */
#ifndef OC_SCALE_NAMES_H
#define OC_SCALE_NAMES_H

const char *const scale_names_short[] = {

    "OFF ",
    "SEMI",
    "IONI",
    "DORI",
    "PHRY",
    "LYDI",
    "MIXO",
    "AEOL",
    "LOCR",
    "BLU+",
    "BLU-",
    "PEN+",
    "PEN-",
    "FOLK",
    "JAPA",
    "GAME",
    "GYPS",
    "ARAB",
    "FLAM",
    "WHOL",
    "PYTH",
    "EB/4",
    "E /4",
    "EA/4",
    "BHAI",
    "GUNA",
    "MARW",
    "SHRI",
    "PURV",
    "BILA",
    "YAMA",
    "KAFI",
    "BHIM",
    "DARB",
    "RAGE",
    "KHAM",

    "BAIR",
    "BTOD",
    "CHAN",
    "KTOD",
    "JOGE",
    "VALL",
    "1322",
    "MANF",
    "MAGC",
    "QUAR",
    "ARMO",
    "HIRA",
    "SCOT",
    "THAI",

    "SEVI",
    "MACH",
    "FATH",
    "BLAC",
    "MAV7",
    "MAV9",
    "SPYT",

    // #ifndef VOR
    "22OR",
    "PAJS",
    "PAJP",
    "PORC",
    "FLAT",
    "LEMB",
    "SENS",
    "53OR",
    "1272",
    "TRIZ",
    "2028",
    "MADG",
    "MARV",
    "PARA",
    "16ED",
    "15ED",
    "14ED",
    "13ED",
    "11ED",
    "10ED",
    "9ED",
    "8ED",
    "7ED",
    "6ED",
    "5ED",
    "16H2",
    "15H2",
    "14H2",
    "13H2",
    "12H2",
    "11H2",
    "10H2",
    "9H2",
    "8H2",
    "7H2",
    "6H2",
    "5H2",
    "4H2",
    // #endif

    "B-Pe",
    "B-Pj",
    "B-Pl",

};

const char *const scale_names[] = {
    "Off",
    "Semitone",
    "Ionian",
    "Dorian",
    "Phrygian",
    "Lydian",
    "Mixolydian",
    "Aeolian",
    "Locrian",
    "Blues major",
    "Blues minor",
    "Pentatonic maj",
    "Pentatonic min",
    "Folk",
    "Japanese",
    "Gamelan",
    "Gypsy",
    "Arabian",
    "Flamenco",
    "Whole tone",
    "Pythagorean",
    "EB/4",
    "E /4",
    "EA/4",
    "Bhairav",
    "Gunakri",
    "Marwa",
    "Shree [Camel]",
    "Purvi",
    "Bilawal",
    "Yaman",
    "Kafi",
    "Bhimpalasree",
    "Darbari",
    "Rageshree",
    "Khamaj",

    "Bairagi",
    "B Todi",
    "Chandradeep",
    "Kaushik Todi",
    "Jogeshwari",

    "Tart.-Vallotti",
    "13of22tETgen=5",
    "Mandelbaum",
    "Magic-in-145tET",
    "Quartaminor3rds",
    "Armodue semi-eq",
    "Hirajoshi",
    "Scot bagpipes",
    "Thai ranat",

    "Sevish12on31EDO",
    "11tetMachine6",
    "13tetFather8",
    "15tetBlackwd10",
    "16tetMavila7",
    "16tetMavila9",
    "17tetSuprpyth12",

    //   #ifndef VOR
    "22tetOrwell9",
    "22tetPajaraSy10",
    "22tetPajara5-10",
    "22tetPorcupine7",
    "26tetFlattone12",
    "26tetLemba10",
    "46tetSensi11",
    "53tetOrwell9",
    "12of72tetRodgrs",
    "TrivalentZeus7",
    "202tetOctone",
    "313tetElfMadag9",
    "MarvelWooGlumma",
    "TOP Parapyth12",
    "16-ED (2 or 3)",
    "15-ED (2 or 3)",
    "14-ED (2 or 3)",
    "13-ED (2 or 3)",
    "11-ED (2 or 3)",
    "10-ED (2 or 3)",
    "9-ED (2 or 3)",
    "8-ED (2 or 3)",
    "7-ED (2 or 3)",
    "6-ED2",
    "5-ED2",
    "16-HD2",
    "15-HD2",
    "14-HD2",
    "13-HD2",
    "12-HD2",
    "11-HD2",
    "10-HD2",
    "9-HD2",
    "8-HD2",
    "7-HD2",
    "6-HD2",
    "5-HD2",
    "4-HD2",
    // #endif

    "Bohlen-Pierce =",
    "Bohlen-Pierce j",
    "Bohlen-Pierce l",
};

#endif //OC_SCALE_NAMES_H